In [ ]:


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42,shuffle=True)#多次运行，四个子集不变
>>> X_train
>>> array([[4, 5],
       [0, 1],
       [6, 7]])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=None,shuffle=True)
>>> X_train
>>> array([[0, 1],
       [6, 7],
       [8, 9]])
       
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42,shuffle=False)#多次运行，四个子集不变
>>> X_train
>>> array([[0, 1],
       [2, 3],
       [4, 5]])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=None,shuffle=False)#结果同random_state=42,shuffle=False



In [2]:
import numpy as np

In [3]:
X = array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
y = [0,1,2,3,4]

NameError: name 'array' is not defined